In [7]:
import cv2
import numpy as np

if __name__ == "__main__":
    im  = cv2.imread(r'./data/1.bmp')
    ref = cv2.imread(r'./data/2.bmp')
    
    number_of_iterations = 50;
    termination_eps = 0.01;
    warpmode   = cv2.MOTION_TRANSLATION
    warpmatrix = np.eye(3, dtype=float)
    print(warpmatrix)

    cv2.findTransformECC (ref, im, warp_matrix, warp_mode,
        cv2.TermCriteria(cv::TermCriteria.COUNT + cv2.TermCriteria.EPS,
        number_of_iterations, termination_eps));
    
    nrow, ncol = ref.shape()
    im2 = np.zeros(nrow, ncol, dtype=float)
    if (warp_mode != cv::MOTION_HOMOGRAPHY)
        cv2.warpAffine(im2, warped_image, warp_matrix, warped_image.size(),
        cv2.INTER_LINEAR + cv2.WARP_INVERSE_MAP);
    else
        cv2.warpPerspective(im2, warped_image, warp_matrix, warped_image.size(),
        cv::INTER_LINEAR + cv::WARP_INVERSE_MAP);
    cout<<"warp matrix is :" << warp_matrix << endl;
        return warped_image;
    
    '''

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
